# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perinfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('doj_rns', models.DateField()),
                ('designation', models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=100)),
                ('email', models.EmailField(help_text='example@rnsit.ac.in', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='areas_of_interest',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('name_of_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('name_of_book', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('year_of_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='expinfo',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('name_of_company', models.CharField(max_length=100)),
                ('position_in_company', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='papers_published',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('name_of_journal', models.CharField(max_length=100)),
                ('year_of_publication', models.DateField()),
                ('link_to_paper', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('name_of_project', models.CharField(max_length=100)),
                ('brief_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='researchinfo',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('name_of_institution', models.CharField(max_length=100)),
                ('area_of_interest', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date_of_completion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='teachinfo',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('name_of_college', models.CharField(max_length=100)),
                ('position_in_college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date_of_completion', models.DateField()),
            ],
        ),
    ]
