# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='overallexp',
            fields=[
                ('idper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formdata.perinfo')),
                ('exp', models.CharField(max_length=100)),
            ],
        ),
    ]
